### ISSUE TITLE
Test file under AGPL-3.0

### ISSUE THREAD

**Issue by hyandell** [vega/vegafusion#478]
Given the project relicensed from AGPL-3.0 to BSD-3-Clause, I wanted to flag that there's still a file under AGPL-3.0 in case that is unintentional.

https://github.com/vega/vegafusion/blob/main/python/vegafusion/tests/test_transformer.py

**Comment by jonmmease** [comment]
Thanks for flagging, yes this was unintentional. I'll update this shortly!

**Comment by jonmmease** [comment]
Removed in https://github.com/vega/vegafusion/pull/479, thanks again!
