### ISSUE TITLE
Should `transformed_data()` also drop the columns that are not included in the spec?

### ISSUE THREAD

**Issue by joelostblom** [vega/vegafusion#484]
Since vegafusion eliminates unused columns from the spec, I wonder if this should be reflected when calling `transformed_data`. For example, with this bar chart, I can still see the unnused columns using `transformed_data`, but if I [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhAATJJhSoA2qHFIEcNCDEMATlDgB9AAzSQxJABsGcCGlUglIAILmmRuONloATAA4ZDwhFPUw0EwBfKVBnACF3T280AQEgoxCkMIjo2O0AYUSvH1QAFgBmdMzs1CiYp20AESLk1ABOAEYq0PDa3Ib0AFEWkv8ukGCenPrnADERlMqJjKm+me0AcQXUDrburN66vPQACW3-AHZ9mqOBkABJbYFfa8PIgF1+9U1tXQNjExGAAeRlkbGQNHERhQMksNjsDmOrhA-XiKPW6EKqKa6KRw2x6HmBJAW2JZ2Jjw+HxkEBoZHUVnsKjUGi06BBITgOHMcNsflu3zZIAA7jRZPRzAwcPJMEKmEhvBAcEhDAAKMEQ8SqgDkQO1AEpKFYvGR6FIAAQmShdS2UEwCfXmgBU5o5su51JAyD0AGsmY5MABPHBCvRwKDhGSC7Tev3mABmenBaFAMucf0MpnRIC8UDYsjZoClMsLICBKZA8ZocCsJQaNKg1iF5eiIEDvgrVZrdcmB3M0Cb2kD2dF4pgFdp9OsMaQQNVVt8aXN8u8o-oOr1+v12eHqFAXdr2g8xX7jeNQ+zVasVgrvKFAGJSlALv4kP4UZFWyFA+eVBMsiAnzvA2Tb+iyPzsuYQYhkeCo+DIGpIJCFZpr8bD6JmgIgohkLQgm1aHugMI6GwNSYHotitnoCpkKWnLcnuOh0gy2hulyH4yMqsiyJCZD3OI4hwHoETWpxSDcbxADyDCysJtR2gIXysheMjQUKViQnAAEIeCSGSIxqHoBmAL4d2-rLNUkbLCenwyNR4i0YiTFTje6DwHSWDoiYwEgAAXkJbBoORthRjQhhBRRcCerOCLMjoZ5CsOMhkHoYoRSFXqQoMQKyuIhwyL5kIFuWtQyFYSBMDWTLxtYEBwDpmpoDVjL1SApHVnl2jGvGVmYGFcaoM1dXJalsgAMoJaxUH9fk6GdYxk4seghg0FYqruWQWAEKUJjbq2yBAtluX5U4qVKENUX1AOv5luYKVpYNtWtX1mA3cR5WVVYLgOb+vgXCYZUVTWcRIHVGmCTGYqyOeMjtV4vQTGw2DJoDn0uBp9LaKlm1WYV3hwCVtzXYl5gfTWkmkHo5UMcFrV48VESqXQN1MOYcPzSA3VWfdJQXUzUA+rNDDzaAi3TstcCretks49tu0fj5XE8Q5KQ0kGN2GNe7gqj6KVzXWwowHQWgyBtnmoOUJhREAA) they are removed.

```py
import altair as alt
import pandas as pd

alt.data_transformers.enable('vegafusion')

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52],
    'c': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

chart = alt.Chart(source).mark_bar().encode(
    x='b',
    y='a'
)
chart.transformed_data()
```

```
	a	b	c	b_start	b_end
0	A	28	28	0.0	28.0
1	B	55	55	0.0	55.0
2	C	43	43	0.0	43.0
3	D	91	91	0.0	91.0
4	E	81	81	0.0	81.0
5	F	53	53	0.0	53.0
6	G	19	19	0.0	19.0
7	H	87	87	0.0	87.0
8	I	52	52	0.0	52.0
```

If my chart specification has a transform, it seems like the unnused columns are also removed in `transformed_data` and the results are the same as in the Vega Editor:

```py
chart = alt.Chart(source).mark_bar().encode(
    x='b',
    y='count()'
)
chart.transformed_data()
```

```
	b	__count
0	28	1
1	55	1
2	43	1
3	91	1
4	81	1
5	53	1
6	19	1
7	87	1
8	52	1
```

**Comment by jonmmease** [comment]
I decided to keep all of the columns so that it's possible to test transforms on a chart without needing to define marks beforehand.

This way you can experiment with the filter transform like this `alt.Chart(source).transform_filter(...).transformed_data()`.  With projection pushdown enabled, all of the columns would be removed in this case because nothing is using them.

And if you're iteratively building a transform pipeline, you may want to `filter` by a column that's not used yet, and so it's not very helpful if `transformed_data` doesn't return columns that aren't already in use.

That said, it could be a parameter option if there's reason to support both behaviors.

**Comment by joelostblom** [comment]
Ah I see, yes that experimentation with `transform_filter` is neat. I mostly wanted to use it to illustrate how VegaFusion works in a lecture by showing that the shape of the data is reduced when it is activated. Since I was working with a really large dataframe, I didn't want to open the vega editor, but just call `shape` on the transformed data. I don't think this is a very important use case and I can just explain what is going on or show in the VegaEditor with data containing less rows, so probably not worth spending implementation time on.

**Comment by jonmmease** [comment]
You could do something like this to demonstrate it:

```
transformed_spec = chart.to_json(format="vega")
print(transformed_spec["data"][0]["values"])
```

Where you need to figure out the right dataset to reference in advance.
